---
- name: Import host_vars in netbox
  connection: local
  hosts: localhost
  gather_facts: false

  collections:
    - netbox.netbox

  vars:
    netbox_token: "{{ lookup('file', '/run/secrets/NETBOX_TOKEN') }}"
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"

  tasks:
    - name: Pause play until netbox is reachable from this host
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/"
        follow_redirects: none
        method: GET
      register: result
      until: result.status == 200
      retries: 720
      delay: 5

    - name: Create local config context
      netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item }}"
          local_context_data: "{{ lookup('file', '/inventory/host_vars/' + item + '.yml') | from_yaml }}"
      loop: "{{ groups['generic'] }}"
      when: "item != 'localhost'"
      ignore_errors: true
